name: over_react_test
version: 2.11.0
description: A library for testing OverReact components
author: Workiva UI Platform Team <uip@workiva.com>
homepage: https://github.com/Workiva/over_react_test/
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  js: ^0.6.1+1
  matcher: ^0.12.1+4
  meta: ^1.1.0
  over_react:
    git:
      url: git@github.com:Workiva/over_react.git
      ref: flutter-fix
  react: ">=5.5.1 <7.0.0"
  test: ^1.9.1

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^2.0.0
  build_web_compilers: ^2.5.1
  dart_dev:
    git:
      url: git@github.com:kyleferguson-wk/dart_dev.git
      ref: master
  dependency_validator:
    git:
      url: git@github.com:kyleferguson-wk/dependency_validator.git
      ref: master
  pedantic: ^1.8.0

transformers:
  - over_react
  - test/pub_serve:
      $include: test/**_test{.*,}.dart